var exports = module.exports = {};

let TAKESCHEDULEDSCREENGRAB = false;
let DEFAULTTIMEOUT = 120 * 1000;
let BROWSERTIMEOUT = 20 * 1000;
let CONCURRENT = 5;
let HEADLESSMODE = true;

exports.TAKESCHEDULEDSCREENGRAB = TAKESCHEDULEDSCREENGRAB;
exports.DEFAULTTIMEOUT = DEFAULTTIMEOUT;
exports.BROWSERTIMEOUT = BROWSERTIMEOUT;
exports.CONCURRENT = CONCURRENT;
exports.HEADLESSMODE = HEADLESSMODE;
