var exports = module.exports = {};

const TAKESCHEDULEDSCREENGRAB = true;
const DEFAULTTIMEOUT = 60 * 1000;
const HEADLESSMODE = false;
const BROWSERTIMEOUT = 10 * 1000;
const CONCURRENT = 1;

exports.TAKESCHEDULEDSCREENGRAB = TAKESCHEDULEDSCREENGRAB;
exports.DEFAULTTIMEOUT = DEFAULTTIMEOUT;
exports.HEADLESSMODE = HEADLESSMODE;
exports.BROWSERTIMEOUT = BROWSERTIMEOUT;
exports.CONCURRENT = CONCURRENT;
